function sumr = Baseline_Perfect_CE_Imperfect_Feedback(Hu, codebook, P, n_power)
% Baseline scheme for Perfect CE & Imperfect Feedback.
% Each user is assumed to have perfect channel vector.
% User channel vector is fed back to the BS using a codebook generated by
% Lloyd algorithm.

[K, M] = size(Hu);

%% Get feedback channel from the users
Hu_Q = zeros(K, M);  % Feedback channel of each user
for u = 1:K
    Hu_test = Hu(u, :);  % size: M x 1
    codebook_u = codebook{u};
    Hu_quant = determine_codeword_Lloyd(codebook_u, Hu_test);
    Hu_Q(u, :) = Hu_quant;
end

%% Compute precoding matrix and rate based on feedback channel with ZF
W_ZF_q = getZF(Hu_Q, P);
[sumr, ~] = getSumRate(Hu,W_ZF_q,n_power);
end

