function sumr = Baseline_ZF_CSIT(Hu, P, n_power)
% Baseline scheme for ZF: CSIT
% BS is assumed to have full CSIT. The precoding matrix is generated by
% ZF algorithm.

%% Compute ZF precoder and rate
W_ZF = getZF(Hu, P);  % ZF: CSIT
[sumr, ~] = getSumRate(Hu,W_ZF,n_power);
end

